services:
  notebook-api:
    build:
      context: .
      target: notebook-api-env
    env_file:
      - ./notebook-api/.env
    ports:
      - 3030:8080
    volumes:
      - ./notebook-api/src:/usr/home/notebook-api/src
      - ./notebook-api/pom.xml:/usr/home/notebook-api/pom.xml
    command: mvn spring-boot:run

  notebook-ui:
    build:
      context: .
      target: notebook-ui-env
    volumes:
      - ./notebook-ui:/usr/home/notebook-ui
    env_file:
      - ./notebook-ui/.env
    environment:
      HOST: 0.0.0.0
      VITE_API_HOSTNAME: notebook-api
      VITE_API_PORT: 8080
    ports:
      - "5173:5173"
      - "3000:3000"
    command: sh -c "npm run build && npm run start"

  postgres-db:
    image: postgres:16
    env_file:
      - ./postgres-db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    user: postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@email.com
      PGADMIN_DEFAULT_PASSWORD: password


volumes:
  db-data: